apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: noteverse-backend-api
  labels:
    app.kubernetes.io/component: backend-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: noteverse-backend-api
  minReplicas: 3
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 65
