apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: noteverse-backend-practice
  labels:
    app.kubernetes.io/component: backend-practice
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: noteverse
      app.kubernetes.io/component: backend-practice
