apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: noteverse-frontend
  labels:
    app.kubernetes.io/component: frontend
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: noteverse
      app.kubernetes.io/component: frontend
