apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: noteverse-backend-api
  labels:
    app.kubernetes.io/component: backend-api
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: noteverse
      app.kubernetes.io/component: backend-api
