apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: noteverse-backend-practice
  labels:
    app.kubernetes.io/component: backend-practice
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: noteverse
      app.kubernetes.io/component: backend-practice
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
