apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend-api-deployment.yaml
  - backend-api-service.yaml
  - backend-practice-deployment.yaml
  - backend-practice-service.yaml
  - model-cache-agent-daemonset.yaml
  - backend-worker-deployment.yaml
  - backend-beat-deployment.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - migration-job.yaml

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: noteverse
      app.kubernetes.io/part-of: noteverse
