"""Pipeline import-job context and shared runtime state."""

import os
import time
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, List, Optional, Protocol, TypedDict

from celery.utils.log import get_task_logger
from sqlalchemy.orm import Session

from app.core.config import settings
from app.modules.import_jobs.schemas import ImportJobProcessingOptions
from app.processing.engines.omr import OmrSuccessResult
from app.modules.import_jobs.worker_service import sync_import_job_service as job_service
from app.pipeline.files_recorder import replace_files
from app.pipeline.step_tracker import StepTracker
from app.modules.import_jobs.artifact_kinds import ImportArtifactKind

if TYPE_CHECKING:
    from app.pipeline.base import Pipeline

logger = get_task_logger(__name__)


class CeleryStateMeta(TypedDict):
    """Progress payload sent back to Celery state updates."""

    status: str
    progress: int
    current_step: str


class CeleryRequestLike(Protocol):
    """Subset of the Celery request object used by task execution."""

    id: str


class CeleryTaskLike(Protocol):
    """Subset of Celery task behavior needed by the pipeline context."""

    request: CeleryRequestLike

    def update_state(self, state: str, meta: CeleryStateMeta) -> None: ...


def _default_job_options() -> ImportJobProcessingOptions:
    """Return an empty typed options payload for new job contexts."""
    return {}


@dataclass
class JobContext:
    """Mutable import-job state shared across pipeline steps."""

    job_id: str
    db: Session
    celery_task: CeleryTaskLike
    image_paths: List[str]
    options: ImportJobProcessingOptions = field(default_factory=_default_job_options)

    raw_paths: List[str] = field(default_factory=list)
    omr_result: Optional[OmrSuccessResult] = None
    main_xml: Optional[str] = None

    job_temp: str = ""
    raw_dir: str = ""
    omr_dir: str = ""

    _start_ts: float = field(default_factory=time.time)
    _deadline: float = 0
    _tracker: StepTracker | None = None
    _order_map: dict[str, int] = field(default_factory=dict)

    def __post_init__(self):
        """Initialize derived paths and timeout state."""
        max_time = int(settings.MAX_PROCESSING_TIME) or 300
        self._deadline = self._start_ts + max_time

        self.job_temp = os.path.join(settings.WORK_ROOT, self.job_id)
        self.raw_dir = os.path.join(self.job_temp, "raw")
        self.omr_dir = os.path.join(self.job_temp, "omr")

        self._tracker = None

    def set_order_map(self, pipeline: "Pipeline") -> None:
        """Bind the runtime step order generated by the pipeline."""
        self._order_map = pipeline.build_order_map()
        self._tracker = StepTracker(self.job_id, self._upsert, self._order_map)

    def _upsert(self, name: str, **kwargs) -> None:
        """Persist step-tracking state."""
        try:
            job_service.upsert_step(self.db, self.job_id, name=name, **kwargs)
        except Exception as exc:
            logger.error(f"[{self.job_id}] _upsert failed for {name}: {exc}")
            self._recover_session()

    def remaining(self) -> int:
        """Return remaining task time in seconds."""
        return max(0, int(self._deadline - time.time()))

    def status(self, state: str, msg: str, prog: int, **kw) -> None:
        """Persist and log task progress updates."""
        try:
            job_service.update_progress(
                self.db,
                self.job_id,
                state,
                prog,
                current_step=kw.get("current_step"),
                code=kw.get("code"),
                error=kw.get("error"),
                started_at=kw.get("started_at"),
            )
        except Exception as exc:
            logger.error(f"[{self.job_id}] update_progress failed: {exc}")
            self._recover_session()

        try:
            step = kw.get("current_step")
            if step and self._tracker:
                self._tracker.on_progress(step)
        except Exception as exc:
            logger.error(f"[{self.job_id}] tracker.on_progress failed: {exc}")

        logger.info(
            f"[{self.job_id}] step={kw.get('current_step') or ''} status={msg} progress={prog}%"
        )

    def _recover_session(self) -> None:
        """Recover a worker session interrupted during a progress update."""
        try:
            self.db.rollback()
        except Exception:
            self.db.invalidate()

    def complete(self) -> None:
        """Finalize successful task execution."""
        try:
            if self._tracker:
                self._tracker.complete_last(final_step_name="ocr_completed")
        except Exception as exc:
            logger.debug(f"[{self.job_id}] tracker.complete_last failed: {exc}")

        if not self.main_xml or not os.path.exists(self.main_xml):
            raise FileNotFoundError("Canonical MusicXML was not produced")
        replace_files(self.job_id, ImportArtifactKind.REVIEW_MUSICXML, [self.main_xml])
        total_time = int(time.time() - self._start_ts)
        job_service.finalize_success(
            self.db, self.job_id, total_time_seconds=total_time
        )
        logger.info(f"[{self.job_id}] Job completed in {total_time}s")

    def update_celery_state(self, status: str, progress: int, current_step: str) -> None:
        """Update the Celery task state payload."""
        self.celery_task.update_state(
            state="RUNNING",
            meta={
                "status": status,
                "progress": progress,
                "current_step": current_step,
            },
        )

    def create_dirs(self) -> None:
        """Create per-job working directories."""
        dirs = [self.raw_dir, self.omr_dir]
        for directory in dirs:
            os.makedirs(directory, exist_ok=True)

    @property
    def is_multi_image(self) -> bool:
        """Return whether the task runs in multi-image mode."""
        return len(self.image_paths) > 1

    @property
    def first_image(self) -> Optional[str]:
        """Return the first copied image path, if any."""
        return self.raw_paths[0] if self.raw_paths else None
