"""Pipeline task context and shared runtime state."""

import os
import time
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, List, Optional, Protocol, TypedDict

from celery.utils.log import get_task_logger
from sqlalchemy.orm import Session

from app.core.config import settings
from app.modules.tasks.schemas import PipelineExecutionFailureResult, TaskProcessingOptions
from app.processing.engines.omr import OmrSuccessResult
from app.modules.tasks.worker_service import sync_task_service as task_service
from app.pipeline.step_tracker import StepTracker

if TYPE_CHECKING:
    from app.pipeline.base import Pipeline

logger = get_task_logger(__name__)


class CeleryStateMeta(TypedDict):
    """Progress payload sent back to Celery state updates."""

    status: str
    progress: int
    current_step: str


class CeleryRequestLike(Protocol):
    """Subset of the Celery request object used by task execution."""

    id: str


class CeleryTaskLike(Protocol):
    """Subset of Celery task behavior needed by the pipeline context."""

    request: CeleryRequestLike

    def update_state(self, state: str, meta: CeleryStateMeta) -> None: ...


def _default_task_options() -> TaskProcessingOptions:
    """Return an empty typed options payload for new task contexts."""
    return {}


@dataclass
class TaskContext:
    """Mutable task state shared across pipeline steps."""

    task_id: str
    db: Session
    celery_task: CeleryTaskLike
    image_paths: List[str]
    options: TaskProcessingOptions = field(default_factory=_default_task_options)

    raw_paths: List[str] = field(default_factory=list)
    pdf_path: Optional[str] = None
    omr_result: Optional[OmrSuccessResult] = None
    main_xml: Optional[str] = None

    task_temp: str = ""
    raw_dir: str = ""
    pdf_dir: str = ""
    omr_dir: str = ""
    xml_dir: str = ""
    preview_dir: str = ""

    _start_ts: float = field(default_factory=time.time)
    _deadline: float = 0
    _tracker: StepTracker | None = None
    _order_map: dict[str, int] = field(default_factory=dict)

    def __post_init__(self):
        """Initialize derived paths and timeout state."""
        max_time = int(settings.MAX_PROCESSING_TIME) or 300
        self._deadline = self._start_ts + max_time

        self.task_temp = os.path.join(settings.WORK_ROOT, self.task_id)
        self.raw_dir = os.path.join(self.task_temp, "raw")
        self.pdf_dir = os.path.join(self.task_temp, "pdf")
        self.omr_dir = os.path.join(self.task_temp, "omr")
        self.xml_dir = os.path.join(self.task_temp, "xml")
        self.preview_dir = os.path.join(self.task_temp, "preview")

        self._tracker = None

    def set_order_map(self, pipeline: "Pipeline") -> None:
        """Bind the runtime step order generated by the pipeline."""
        self._order_map = pipeline.build_order_map()
        self._tracker = StepTracker(self.task_id, self._upsert, self._order_map)

    def _upsert(self, name: str, **kwargs) -> None:
        """Persist step-tracking state."""
        try:
            task_service.upsert_step(self.db, self.task_id, name=name, **kwargs)
        except Exception as exc:
            logger.error(f"[{self.task_id}] _upsert failed for {name}: {exc}")
            self._recover_session()

    def remaining(self) -> int:
        """Return remaining task time in seconds."""
        return max(0, int(self._deadline - time.time()))

    def status(self, state: str, msg: str, prog: int, **kw) -> None:
        """Persist and log task progress updates."""
        try:
            task_service.update_progress(
                self.db,
                self.task_id,
                state,
                prog,
                current_step=kw.get("current_step"),
                code=kw.get("code"),
                error=kw.get("error"),
                started_at=kw.get("started_at"),
            )
        except Exception as exc:
            logger.error(f"[{self.task_id}] update_progress failed: {exc}")
            self._recover_session()

        try:
            step = kw.get("current_step")
            if step and self._tracker:
                self._tracker.on_progress(step)
        except Exception as exc:
            logger.error(f"[{self.task_id}] tracker.on_progress failed: {exc}")

        logger.info(
            f"[{self.task_id}] step={kw.get('current_step') or ''} status={msg} progress={prog}%"
        )

    def _recover_session(self) -> None:
        """Recover a worker session interrupted during a progress update."""
        try:
            self.db.rollback()
        except Exception:
            self.db.invalidate()

    def fail(
        self,
        error: str,
        error_type: str = "Error",
        code: str = "unknown_error",
        current_step: str = "initialization",
    ) -> PipelineExecutionFailureResult:
        """Mark the task as failed and return a standard error payload."""
        self.status(
            "FAILURE",
            "failed",
            0,
            error=error,
            error_type=error_type,
            code=code,
            current_step=current_step,
        )
        return {"success": False, "error": error}

    def complete(self) -> None:
        """Finalize successful task execution."""
        try:
            if self._tracker:
                self._tracker.complete_last(final_step_name="ocr_completed")
        except Exception as exc:
            logger.debug(f"[{self.task_id}] tracker.complete_last failed: {exc}")

        try:
            total_time = int(time.time() - self._start_ts)
            task_service.finalize_success(
                self.db, self.task_id, total_time_seconds=total_time
            )
            logger.info(f"[{self.task_id}] Task completed in {total_time}s")
        except Exception as exc:
            logger.warning(f"[{self.task_id}] finalize_success failed: {exc}")

    def update_celery_state(self, status: str, progress: int, current_step: str) -> None:
        """Update the Celery task state payload."""
        self.celery_task.update_state(
            state="PROGRESS",
            meta={
                "status": status,
                "progress": progress,
                "current_step": current_step,
            },
        )

    def create_dirs(self, include_pdf: bool = False) -> None:
        """Create per-task working directories."""
        dirs = [self.raw_dir, self.omr_dir, self.xml_dir, self.preview_dir]
        if include_pdf:
            dirs.append(self.pdf_dir)

        for directory in dirs:
            os.makedirs(directory, exist_ok=True)

    @property
    def is_multi_image(self) -> bool:
        """Return whether the task runs in multi-image mode."""
        return len(self.image_paths) > 1

    @property
    def first_image(self) -> Optional[str]:
        """Return the first copied image path, if any."""
        return self.raw_paths[0] if self.raw_paths else None
