version: 2
updates:
  - package-ecosystem: npm
    directory: /apps/customer-web
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    commit-message:
      prefix: chore
      prefix-development: chore
      include: scope
    groups:
      non-breaking:
        update-types: [minor, patch]

  - package-ecosystem: npm
    directory: /apps/platform-admin
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    commit-message:
      prefix: chore
      prefix-development: chore
      include: scope
    groups:
      non-breaking:
        update-types: [minor, patch]

  - package-ecosystem: pip
    directory: /backend
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    commit-message:
      prefix: chore
      prefix-development: chore
      include: scope
    groups:
      non-breaking:
        update-types: [minor, patch]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: docker
    directory: /docker/backend
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: docker
    directory: /docker/customer-web
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: docker
    directory: /docker/platform-admin
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: docker
    directory: /docker/transcoda
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    commit-message:
      prefix: chore
      include: scope
