ARG PRACTICE_DEPS_IMAGE=noteverse-backend-practice-deps:dev

FROM ${PRACTICE_DEPS_IMAGE}

WORKDIR /app

RUN python -m pip install --upgrade pip setuptools wheel \
    && python -m pip install -r /tmp/requirements/quality-tools.txt

COPY backend/ /app/

CMD ["bash"]
