apiVersion: apps/v1
kind: Deployment
metadata:
  name: noteverse-backend-worker
  labels:
    app.kubernetes.io/component: backend-worker
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: noteverse
      app.kubernetes.io/part-of: noteverse
      app.kubernetes.io/component: backend-worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: noteverse
        app.kubernetes.io/part-of: noteverse
        app.kubernetes.io/component: backend-worker
    spec:
      imagePullSecrets:
        - name: noteverse-registry-credentials
      containers:
        - name: worker
          image: ghcr.io/tinghui0912/noteverse/backend-worker@sha256:54112e287f4c6861a4e5b6d84ab35746a1ee9e0583fd034ece1d0811175742e2
          args:
            - worker
          envFrom:
            - configMapRef:
                name: noteverse-backend-config
            - secretRef:
                name: noteverse-backend-secret
          resources:
            requests:
              cpu: "1"
              memory: 4Gi
            limits:
              cpu: "4"
              memory: 12Gi
