apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: noteverse-staging

resources:
  - base
  - gateway.yaml

labels:
  - includeSelectors: false
    includeTemplates: true
    pairs:
      app.kubernetes.io/instance: noteverse-staging
      app.kubernetes.io/environment: staging

images:
  - name: noteverse-backend-api
    newName: ghcr.io/tinghui0912/noteverse/backend-api
    digest: sha256:02699120696c47c1da3eca6c053c7f5458776fcd14e9b3fb6143b81cf6ed53a5
  - name: noteverse-backend-practice
    newName: ghcr.io/tinghui0912/noteverse/backend-practice
    digest: sha256:2f59c22d33fafb26ae7f2b74b2a67c54d47f998db0e44ef2a1d7079d849f8ed1
  - name: noteverse-backend-worker
    newName: ghcr.io/tinghui0912/noteverse/backend-worker
    digest: sha256:54112e287f4c6861a4e5b6d84ab35746a1ee9e0583fd034ece1d0811175742e2
  - name: noteverse-backend-beat
    newName: ghcr.io/tinghui0912/noteverse/backend-beat
    digest: sha256:eab8300db40472901824805519113c4827087e34f76f5738731e7fe4fd7c3b70
  - name: noteverse-frontend
    newName: ghcr.io/tinghui0912/noteverse/frontend
    digest: sha256:e1e474beb7728cd08c05423402b988c700a6a8e6534068439593d0aa8eea1b43
  - name: noteverse-platform-admin
    newName: ghcr.io/tinghui0912/noteverse/platform-admin
    digest: sha256:939e504a20819edadc740e3b0d16978a81be34a32d4bc1d9e0b1a0b835396f1e

  - name: busybox
    newName: busybox
    digest: sha256:73aaf090f3d85aa34ee199857f03fa3a95c8ede2ffd4cc2cdb5b94e566b11662

configMapGenerator:
  - name: noteverse-backend-config
    envs:
      - backend-config.env
  - name: noteverse-frontend-config
    envs:
      - frontend-config.env
  - name: noteverse-control-plane-config
    envs:
      - control-plane-config.env

generatorOptions:
  disableNameSuffixHash: true

replicas:
  - name: noteverse-backend-api
    count: 1
  - name: noteverse-control-plane
    count: 1
  - name: noteverse-backend-practice
    count: 1
  - name: noteverse-backend-worker
    count: 0
  - name: noteverse-frontend
    count: 1
  - name: noteverse-platform-admin
    count: 1

patches:
  - path: patch-backend-worker-scheduling.yaml
  - path: patch-backend-api-runtime-volumes.yaml
  - path: patch-backend-practice-runtime-volumes.yaml
  - path: patch-backend-worker-runtime-volumes.yaml
  - path: patch-backend-beat-runtime-volumes.yaml
