apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: noteverse-staging

resources:
  - base
  - gateway.yaml

labels:
  - includeSelectors: false
    includeTemplates: true
    pairs:
      app.kubernetes.io/instance: noteverse-staging
      app.kubernetes.io/environment: staging

images:
  - name: noteverse-backend-api
    newName: ghcr.io/tinghui0912/noteverse/backend-api
    digest: sha256:43b83ebae5c40a5e8f4c1d9d397298a70f44e71ffe3154eb1cf7ead9e53c4e32
  - name: noteverse-backend-practice
    newName: ghcr.io/tinghui0912/noteverse/backend-practice
    digest: sha256:48617b12c66cfaa5043a1a0a4e939f729910c7bf9fac2f081fb332cb318c3ea7
  - name: noteverse-backend-worker
    newName: ghcr.io/tinghui0912/noteverse/backend-worker
    digest: sha256:54112e287f4c6861a4e5b6d84ab35746a1ee9e0583fd034ece1d0811175742e2
  - name: noteverse-backend-beat
    newName: ghcr.io/tinghui0912/noteverse/backend-beat
    digest: sha256:6431e801e0b0fbe296d9b6e66d63d7bae23404288f73cdcb3540dbc5e58d54c2
  - name: noteverse-frontend
    newName: ghcr.io/tinghui0912/noteverse/frontend
    digest: sha256:e1e474beb7728cd08c05423402b988c700a6a8e6534068439593d0aa8eea1b43

  - name: busybox
    newName: busybox
    digest: sha256:73aaf090f3d85aa34ee199857f03fa3a95c8ede2ffd4cc2cdb5b94e566b11662

configMapGenerator:
  - name: noteverse-backend-config
    envs:
      - backend-config.env
  - name: noteverse-frontend-config
    envs:
      - frontend-config.env

generatorOptions:
  disableNameSuffixHash: true

replicas:
  - name: noteverse-backend-api
    count: 1
  - name: noteverse-backend-practice
    count: 1
  - name: noteverse-backend-worker
    count: 0
  - name: noteverse-frontend
    count: 1

patches:
  - path: patch-backend-worker-scheduling.yaml
  - path: patch-backend-api-runtime-volumes.yaml
  - path: patch-backend-practice-runtime-volumes.yaml
  - path: patch-backend-worker-runtime-volumes.yaml
  - path: patch-backend-beat-runtime-volumes.yaml
