"""Preview-image generation step."""

import glob
import os
from typing import Optional, cast

from celery.utils.log import get_task_logger

from app.core.exceptions import (
    MuseScoreFailedException,
    MuseScoreMissingException,
    TimeoutException,
)

from ..base import Step
from ..context import TaskContext

logger = get_task_logger(__name__)


class PreviewGenerationStep(Step):
    """Render one or more preview images from the current MusicXML file."""

    name = "preview_generation"
    progress_start = 90
    progress_end = 98

    def run(self, ctx: TaskContext) -> None:
        from app.core.config import settings
        from app.processing.engines.musescore import MuseScoreEngine, MuseScoreSuccessResult

        main_xml = ctx.main_xml
        if not main_xml or not os.path.exists(main_xml):
            raise MuseScoreFailedException(details={"reason": "xml_not_found"})

        musescore_path = settings.MUSESCORE_PATH
        if not musescore_path or not os.path.exists(musescore_path):
            raise MuseScoreMissingException()
        if ctx.remaining() <= 0:
            raise TimeoutException(details={"error": "Task deadline exceeded before preview generation"})

        logger.info(f"[{ctx.task_id}] Starting preview generation")

        engine = MuseScoreEngine(
            musescore_path=musescore_path,
            output_folder=ctx.preview_dir,
            timeout_seconds=ctx.remaining(),
        )

        try:
            result = engine.render_to_image(
                xml_path=main_xml,
                output_name="preview",
                format="png",
                dpi=300,
            )

            if not result.get("success"):
                failure_result = result
                if failure_result.get("code") == "task_timeout":
                    raise TimeoutException(details={"error": failure_result.get("error")})
                raise MuseScoreFailedException(details={"error": failure_result.get("error")})

            success_result = cast(MuseScoreSuccessResult, result)

            preview_images = self._collect_preview_images(
                ctx.preview_dir,
                success_result["output_path"],
            )

            if preview_images:
                try:
                    from app.shared.file_kinds import FileKind
                    from app.pipeline.files_recorder import replace_files

                    replace_files(
                        ctx.task_id,
                        FileKind.PREVIEW_IMAGE,
                        preview_images,
                        dpi=300,
                    )
                    logger.info(f"[{ctx.task_id}] Recorded {len(preview_images)} preview images")
                except Exception as exc:
                    logger.warning(f"[{ctx.task_id}] Failed to record preview_image: {exc}")

            logger.info(f"[{ctx.task_id}] Preview generation completed: {preview_images}")
        except MuseScoreFailedException:
            raise
        except Exception as exc:
            logger.error(f"[{ctx.task_id}] Preview generation failed: {exc}")
            raise MuseScoreFailedException(details={"error": str(exc)})

    def _collect_preview_images(self, preview_dir: str, output_path: Optional[str]) -> list[str]:
        """Collect all preview images generated by MuseScore."""
        images: list[str] = []

        if output_path and os.path.isabs(output_path):
            full_out = output_path
        elif output_path:
            full_out = os.path.join(preview_dir, os.path.basename(output_path))
        else:
            full_out = os.path.join(preview_dir, "preview.png")

        base, ext = os.path.splitext(full_out)

        if base.endswith("-1"):
            base_core = base[:-2]
            index = 1
            while True:
                candidate = f"{base_core}-{index}{ext}"
                if not os.path.exists(candidate):
                    break
                images.append(os.path.abspath(candidate))
                index += 1
        elif os.path.exists(full_out):
            images.append(os.path.abspath(full_out))
        else:
            pattern = os.path.join(preview_dir, "preview-*.png")
            found = sorted(glob.glob(pattern))
            images = [os.path.abspath(found_path) for found_path in found]

        return images
