apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend-api-servicemonitor.yaml
  - backend-practice-servicemonitor.yaml
  - observability-exporter-servicemonitor.yaml
  - noteverse-application-prometheusrule.yaml
